### ISSUE TITLE
[feat]: Design Login page

### ISSUE THREAD

**Issue by NiazMorshed2007** [NiazMorshed2007/twitter#3]
### Design the login page in `pages/auth/login.jsx`

Few things to keep in mind:
- Choose design of your own
- Keep it simple
- Use colors written `tailwind.config` file (add if needed)

**Comment by LeonardoLopesHonda** [comment]
can I work on this? Don't need to do any functionality right, just the style?

**Comment by NiazMorshed2007** [comment]
@LeonardoLopesHonda right. Feel free to take!

**Comment by Eclipse175** [comment]
oof i wanted to do this but lets see what we get in the future
