### ISSUE TITLE
(feat): Design signup page

### ISSUE THREAD

**Issue by NiazMorshed2007** [NiazMorshed2007/twitter#4]
Design the signup page in `pages/auth/signup.jsx`

Few things to keep in mind:

- Choose design of your own
- Keep it simple
- Use colors written `tailwind.config` file (add if needed)

**Comment by LeonardoLopesHonda** [comment]
I'm going to do this one too, is there any problem doing the push in a different branch or do you need to do it in the main? The last one I did was not notified in the issue

**Comment by LeonardoLopesHonda** [comment]
Sign Up page:
![image](https://user-images.githubusercontent.com/83879739/232498546-8194dc21-adac-4399-b111-f4def34243b5.png)
